services:
  postgres:
    image: postgres:16
    container_name: chorus-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chorus
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chorus"]
      interval: 5s
      timeout: 3s
      retries: 10
  controller:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/chorus?sslmode=disable
      WORKER_GRPC_ADDR: localhost:9670
      HTTP_PORT: "8081"
    ports:
      - "8081:8081"