basePath: /
definitions:
  domain.CreateReplicationRequest:
    properties:
      agent_url:
        type: string
      buckets:
        items:
          type: string
        type: array
      from:
        type: string
      to:
        type: string
      to_bucket:
        type: string
      user:
        type: string
    required:
    - from
    - to
    - user
    type: object
  domain.CreateStorageRequest:
    properties:
      access_key:
        example: AKIA123
        type: string
      address:
        example: http://localhost:9000
        type: string
      name:
        example: my-storage
        type: string
      provider:
        example: minio
        type: string
      secret_key:
        example: SECRET123
        type: string
      user:
        example: myuser
        type: string
    required:
    - access_key
    - address
    - name
    - provider
    - secret_key
    - user
    type: object
  domain.ReplicationIdentifier:
    properties:
      bucket:
        type: string
      from:
        type: string
      to:
        type: string
      to_bucket:
        type: string
      user:
        type: string
    required:
    - bucket
    - from
    - to
    - user
    type: object
  domain.Storage:
    properties:
      address:
        type: string
      credentials:
        items:
          $ref: '#/definitions/domain.StorageCredential'
        type: array
      default_region:
        type: string
      health_check_interval_ms:
        type: integer
      http_timeout_ms:
        type: integer
      id:
        type: string
      is_main:
        type: boolean
      is_secure:
        type: boolean
      name:
        type: string
      provider:
        type: string
      rate_limit_enabled:
        type: boolean
      rate_limit_rpm:
        type: integer
    type: object
  domain.StorageCredential:
    properties:
      access_key_id:
        type: string
      id:
        type: string
      secret_access_key:
        type: string
      storage_id:
        type: string
      user:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: A control plane for Chorus Worker that manages S3 replication jobs
  title: Chorus Controller API
  version: "1.0"
paths:
  /buckets:
    get:
      consumes:
      - application/json
      description: Returns a list of buckets that can be used for replication jobs
        between specified storages
      parameters:
      - description: User identifier
        in: query
        name: user
        type: string
      - description: Source storage name
        in: query
        name: from
        type: string
      - description: Destination storage name
        in: query
        name: to
        type: string
      - description: Whether to show already replicated buckets
        in: query
        name: show_replicated
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: List buckets available for replication
      tags:
      - buckets
  /health:
    get:
      consumes:
      - application/json
      description: Returns the health status of the controller
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - health
  /replications:
    delete:
      consumes:
      - application/json
      description: Deletes a replication job
      parameters:
      - description: Replication identifier
        in: body
        name: replication
        required: true
        schema:
          $ref: '#/definitions/domain.ReplicationIdentifier'
      produces:
      - application/json
      responses:
        "200":
          description: Replication deleted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: Delete a replication job
      tags:
      - replications
    get:
      consumes:
      - application/json
      description: Returns a list of all configured replication jobs with their statuses
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: object
            type: array
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: List all replication jobs
      tags:
      - replications
    post:
      consumes:
      - application/json
      description: Configures a new replication job for specified buckets between
        storages
      parameters:
      - description: Replication configuration
        in: body
        name: replication
        required: true
        schema:
          $ref: '#/definitions/domain.CreateReplicationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Replication job created successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: Create a new replication job
      tags:
      - replications
  /replications/pause:
    post:
      consumes:
      - application/json
      description: Pauses an active replication job
      parameters:
      - description: Replication identifier
        in: body
        name: replication
        required: true
        schema:
          $ref: '#/definitions/domain.ReplicationIdentifier'
      produces:
      - application/json
      responses:
        "200":
          description: Replication paused successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: Pause a replication job
      tags:
      - replications
  /replications/resume:
    post:
      consumes:
      - application/json
      description: Resumes a paused replication job
      parameters:
      - description: Replication identifier
        in: body
        name: replication
        required: true
        schema:
          $ref: '#/definitions/domain.ReplicationIdentifier'
      produces:
      - application/json
      responses:
        "200":
          description: Replication resumed successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: Resume a paused replication job
      tags:
      - replications
  /replications/switch/zero-downtime:
    post:
      consumes:
      - application/json
      description: Switches main and follower buckets for a replication job without
        blocking writes
      parameters:
      - description: Replication identifier
        in: body
        name: replication
        required: true
        schema:
          $ref: '#/definitions/domain.ReplicationIdentifier'
      produces:
      - application/json
      responses:
        "202":
          description: Switch initiated successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: Switch main and follower buckets without downtime
      tags:
      - replications
  /storages:
    get:
      consumes:
      - application/json
      description: Returns a list of all configured storage backends
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties: true
            type: object
      summary: List all storages
      tags:
      - storages
    post:
      consumes:
      - application/json
      description: Creates a storage with simplified parameters. All other settings
        use default values.
      parameters:
      - description: Storage creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateStorageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Storage created successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create a storage configuration
      tags:
      - storages
  /storages/{id}:
    delete:
      description: Deletes a storage and all its credentials
      parameters:
      - description: Storage ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Storage deleted successfully
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Delete a storage configuration
      tags:
      - storages
    get:
      parameters:
      - description: Storage ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Storage'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get storage by ID
      tags:
      - storages
    put:
      consumes:
      - application/json
      description: Updates an existing storage with new parameters
      parameters:
      - description: Storage ID
        in: path
        name: id
        required: true
        type: string
      - description: Storage update request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.CreateStorageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Storage updated successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Update a storage configuration
      tags:
      - storages
  /storages/db:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Storage'
            type: array
      summary: List storages from DB
      tags:
      - storages
schemes:
- http
swagger: "2.0"
